// <auto-generated />
namespace HealthObservations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddMeasurements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMeasurements));
        
        string IMigrationMetadata.Id
        {
            get { return "201512081912289_AddMeasurements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
