// <auto-generated />
namespace HealthObservations.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class v001update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v001update));
        
        string IMigrationMetadata.Id
        {
            get { return "201512120240173_v001-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
